name: Test build

on:
  push:
    branches:
      - main
      - rc
  pull_request:
    branches:
      - main
      - rc
      - dev

env:
    SOURCENAME: VIP-Core
    TEST_PLUGIN: vip_module_test

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm_version: ["1.10", "1.11", "1.12"]
      fail-fast: false

    steps:
        - uses: actions/checkout@v2

        - name: Set environment variables
          run: |
            echo SCRIPTS_PATH=$(pwd) >> $GITHUB_ENV
            echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
        - name: Echo version
          run: |
            echo $RELEASE_VERSION
            echo ${{ env.RELEASE_VERSION }}
            
        - name: Setup SourcePawn Compiler ${{ matrix.sm_version }}
          id: setup_sp
          uses: rumblefrog/setup-sp@master
          with:
            version: ${{ matrix.sm_version }}
            version-file: ./scripting/${{ env.SOURCENAME }}.sp

        - name: Compile plugin ${{ env.SOURCENAME }}
          run: |
            mkdir plugins
            cd scripting
            echo '#define PL_VERSION "${{ env.RELEASE_VERSION }} [build: ${{ env.GITHUB_SHA_SHORT }}]"' > include/vip_version.inc
            spcomp -w234 -E -O2 -v2 -i"include" -o"../plugins/${{ env.SOURCENAME }}.smx" ${{ env.SOURCENAME }}.sp
            echo "===OUT FILES==="
            cd ../plugins
            ls
            echo "===VERSION==="
            echo ${{ env.GITHUB_SHA_SHORT }}
          working-directory: ${{ env.SCRIPTS_PATH }}
        
        - name: Compile test plugin ${{ env.SOURCENAME }}
          run: |
            cd scripting
            spcomp -w234 -E -O2 -v2 -i"include" -o"../plugins/${{ env.TEST_PLUGIN }}.smx" ${{ env.TEST_PLUGIN }}.sp
            echo "===OUT FILES==="
            cd ../plugins
            ls
            echo "===VERSION===
            echo ${{ env.GITHUB_SHA_SHORT }}
          working-directory: ${{ env.SCRIPTS_PATH }}